version: "3"

services:
  composer:
    image: composer
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
  php:
    image: php:8-cli
    volumes:
      - .:/app
    working_dir: /app
